### ISSUE TITLE
Issue with migration

### ISSUE THREAD

**Issue by majestic44** [forumify/perscom-migrator#2]
im having an issue with the migration of data after installing the plugin and configuring settings with the required data.

Error: Class "\IPS\perscom\Personnel\Status" not found (0)
#0 /home/goldenco/public_html/applications/perscommigrator/modules/admin/migrate/migrate.php(43): IPS\Helpers\Form\_Node->__construct('status_blacklis...', NULL, false, Array, NULL, NULL, '<span class="ip...')
#1 /home/goldenco/public_html/system/Dispatcher/Controller.php(118): IPS\perscommigrator\modules\admin\migrate\_migrate->manage()
#2 /home/goldenco/public_html/applications/perscommigrator/modules/admin/migrate/migrate.php(26): IPS\Dispatcher\_Controller->execute()
#3 /home/goldenco/public_html/system/Dispatcher/Dispatcher.php(153): IPS\perscommigrator\modules\admin\migrate\_migrate->execute()
#4 /home/goldenco/public_html/admin/index.php(13): IPS\_Dispatcher->run()
#5 {main}

**Comment by jannes-io** [comment]
Hmm, that's odd.

Could you give me the version of the PERSCOM application? You can find this in your admin control panel, under applications.

**Comment by jannes-io** [comment]
No response. Closing issue.
